# Assignment 5
## Data Preprocessing

We will be using a dataframe created from *Income Dirty Data.csv*. Download the file from D2L. 

1. Import the following modules
    - `pandas`
    - `numpy`
    - `preprocessing` from `sklearn` (for bonus question)
    - `KNNImputer` from `sklearn.impute` (for bonus question)
2. Create your dataframe from the file using `pandas`

In [43]:
import pandas as pd
import numpy as np
from sklearn import preprocessing as prep
from sklearn.impute import KNNImputer as KNNI

df = pd.read_csv("./Income Dirty Data.csv")

df.head()

   ID     sex  age    income  tax_15_pct
0   1   Women   21  147168.0    22075.20
1   2  Female   29  119595.0    17939.25
2   3  Female   56   87770.0    13165.50
3   4     NaN   21   54259.0     8138.85
4   5    Male   28       NaN   160230.00

3. Calculate and display the following information
    - Total number of NaN values for **each column**
    - Percentage of NaN values in the dataset 
    - Number of rows *without* any NaN values

In [44]:
def missing_values():
    print("Missing values per column:")
    null_values = df.isna().sum()
    print(null_values.to_string())

    print("\nPercentage of missing values:")
    pct_missing = null_values.sum()/(len(df) * len(df.columns))
    print(f"{pct_missing * 100:.2F}%")

    print("\nNumber of rows WITHOUT any missing values:")
    rows_with_missing = len((df[(df.income.isna()) | (df.tax_15_pct.isna())]))
    print(len(df) - rows_with_missing)

missing_values()

Missing values per column:
ID              0
sex            88
age             0
income        109
tax_15_pct     93

Percentage of missing values:
5.80%

Number of rows WITHOUT any missing values:
806

Besides missing values (NaN), the dataset contains errors. We have the following rules to check:

* All employees are adults (18+ years old)
* All employees pay 15% of their income for the tax
* All employees make money; no income should be <= 0 
---
4. Calculate and display the percentage of the data that does **NOT** violate any **one** of the rules.

In [50]:
rule1 = df["age"] >= 18 
rule2 = df["income"] * 0.15 == df["tax_15_pct"]
rule3 = df["income"] > 0

all_rules = rule1 & rule2 & rule3

print(f"{all_rules.sum()/len(all_rules) * 100:.2F}%")

47.00%

Now that we have determined the number of erroneous datapoints in our set, let's work on correcting it as best we can.

5. Replace non *Female*/*Male* values in the **Sex** column with either *Female* or *Male* (e.g., Women --> Female)

In [7]:
df["sex"] = df["sex"].replace(["Man", "Men"], "Male", regex=True)
df["sex"] = df["sex"].replace(["Woman", "Women"], "Female", regex=True)

df.to_csv("./Income Dirty Data.csv")

6. Replace non-positive **Age** values with NaN (`numpy.NaN`)
7. Replace non-positive **Income** values with NaN (`numpy.NaN`)
8. Replace non-positive **Tax (15%)** values with NaN (`numpy.NaN`)

In [ ]:
df["age"] = np.where(df["age"] < 0, np.nan, df["age"])

df["income"] = np.where(df["income"] < 0, np.nan, df["income"])

df["tax_15_pct"] = np.where(df["tax_15_pct"] < 0, np.nan, df["tax_15_pct"])

df.head(20)

    ID     sex   age    income  tax_15_pct
0    1   Women  21.0  147168.0    22075.20
1    2  Female  29.0  119595.0    17939.25
2    3  Female  56.0   87770.0    13165.50
3    4     NaN  21.0   54259.0     8138.85
4    5    Male  28.0       NaN   160230.00
5    6   Woman   0.0  128326.0    19248.90
6    7  Female   NaN       NaN         NaN
7    8  Female  24.0       NaN    11820.60
8    9  Female  38.0  149473.0    22420.95
9   10     Man  48.0  113663.0  1136630.00
10  11   Woman  33.0   96649.0    14497.35
11  12    Male  55.0       NaN     9776.25
12  13     Man  52.0   64944.0     9741.60
13  14    Male  47.0   85300.0         NaN
14  15     Men  45.0   80091.0    12013.65
15  16   Women  25.0   56418.0     8462.70
16  17  Female  45.0   54189.0     8128.35
17  18    Male  29.0   67489.0    10123.35
18  19    Male  48.0  137978.0    20696.70
19  20  Female   NaN   89991.0         NaN

The following question is a bonus (+10) question, but I'd encourage you to give it a try!

9. Use machine learning (`KNNImputer`) to impute all missing values (replaces NaN values with the most predicted values)
    - Will need to use a scaler and convert the values in the **Sex** column to a numeric value for algorithm to work properly
    - Show some of the data prior to imputing, and after imputing

In [1]:
print("I don't wanna")

I don't wanna

10. In the empty `Markdown` cell below, explain why it is important to clean a dataset before calculating analytics about the data

It is important to clean data because dirty data can fudge numbers and cause calculations/predictions to be more inaccurate than if it were clean.

10. Submit this `Jupyter` file to D2L, renamed as **Last_First_Assignment4.ipynb** 
    - Replace '**Last**' and '**First**' with your name